# Generated by Django 4.0.4 on 2022-05-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.FilePathField(blank=True, null=True, path='/img'),
        ),
    ]
